### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by bartonhammond** [Vitalizzzer/cucumber-json-report-formatter#18] opened 2022-11-15 16:42 UTC
I upgraded to version 0.1.4 and still get this error when running tests.

```
C:\Users\hammonbu\git\smc-cypress\node_modules\cucumber-json-report-formatter\lib\formatter.js:151
            parsed.pickle.steps.forEach(step => {
                                ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at C:\Users\hammonbu\git\smc-cypress\node_modules\cucumber-json-report-formatter\lib\formatter.js:151:33
    at Array.forEach (<anonymous>)
    at Formatter.getPickleText (C:\Users\hammonbu\git\smc-cypress\node_modules\cucumber-json-report-formatter\lib\formatter.js:149:20)
    at Formatter.getStepText (C:\Users\hammonbu\git\smc-cypress\node_modules\cucumber-json-report-formatter\lib\formatter.js:144:27)
    at Formatter.createStepJson (C:\Users\hammonbu\git\smc-cypress\node_modules\cucumber-json-report-formatter\lib\formatter.js:96:27)
    at C:\Users\hammonbu\git\smc-cypress\node_modules\cucumber-json-report-formatter\lib\formatter.js:46:41
    at Array.forEach (<anonymous>)
    at C:\Users\hammonbu\git\smc-cypress\node_modules\cucumber-json-report-formatter\lib\formatter.js:45:42
    at Array.forEach (<anonymous>)
    at C:\Users\hammonbu\git\smc-cypress\node_modules\cucumber-json-report-formatter\lib\formatter.js:32:23
An error was thrown in your plugins file while executing the handler for the after:run event.

The error we received was:

Error: node exited non-successfully
    at ChildProcess.<anonymous> (C:\Users\hammonbu\git\smc-cypress\node_modules\@badeball\cypress-cucumber-preprocessor\lib\add-cucumber-preprocessor-plugin.js:92:32)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by vrymar** [comment] 2022-11-18 07:58
Hi @bartonhammond ! Could you please provide your cucumber-messages.ndjson file?

**Comment by bartonhammond** [comment] 2022-11-21 16:13
Added the folder `cucumber-json`

[cucumber-json.zip](https://github.com/Vitalizzzer/cucumber-json-report-formatter/files/10058154/cucumber-json.zip)

**Comment by bartonhammond** [comment] 2022-11-21 18:12
This is w/ ` "cucumber-json-report-formatter": "0.1.4",`
[cucumber-json.zip](https://github.com/Vitalizzzer/cucumber-json-report-formatter/files/10059375/cucumber-json.zip)

**Comment by vitaliirymar** [comment] 2022-12-09 15:11
Hi @bartonhammond ! I've noticed that the provided `messages.ndjson ` doesn't have `steps` block in the last `pickle`. That's why it can't be parsed.
![TEMP_DATA_messages ndjson](https://user-images.githubusercontent.com/102508788/206732925-ad3c608d-c8ef-48d0-917b-86b5b6ec43a9.png)

**Comment by bartonhammond** [comment] 2022-12-13 15:41
I think the reason for this exception is that this Feature file has multiple Scenarios and two of them have `@focus` .  These 2 Scenarios are in the middle, above the Scenario `Manage Assessments pull standard costs for dismissed felony charge and fully disposed/sentenced Misdemeanor charge  - Non violations bureau`  - this scenario is not processed since it doesn't have `@focus`.  The same w/ the following Scenario in the image above.  They are below the Scenarios that have `@focus` and thus do not have any Steps that were run.

Hope that helps

**Comment by vrymar** [comment] 2022-12-16 08:17
Anyway, looks like the @badeball/cypress-cucumber-preprocessor generates irrelevant *.ndjson file.

**Comment by vrymar** [comment] 2023-02-24 19:21
Closing the issue as not caused by this tool

**Closed as completed by vrymar** 2023-02-24 19:21 UTC
